package com.javaweb.model;
// Generated Oct 28, 2016 8:20:18 AM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private String chucnang;
     private double gia;
     private String ghichu;
     private String image;

    public Sanpham() {
    }

	
    public Sanpham(String ten, String chucnang, double gia) {
        this.ten = ten;
        this.chucnang = chucnang;
        this.gia = gia;
    }
    public Sanpham(String ten, String chucnang, double gia, String ghichu, String image) {
       this.ten = ten;
       this.chucnang = chucnang;
       this.gia = gia;
       this.ghichu = ghichu;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getChucnang() {
        return this.chucnang;
    }
    
    public void setChucnang(String chucnang) {
        this.chucnang = chucnang;
    }
    public double getGia() {
        return this.gia;
    }
    
    public void setGia(double gia) {
        this.gia = gia;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


