package com.javaweb.model;
// Generated Oct 28, 2016 8:20:18 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int idUser;
     private String userName;
     private String email;
     private String pwd;
     private String fullName;
     private String gender;
     private String avatar;

    public Users() {
    }

	
    public Users(int idUser, String userName, String email, String pwd, String fullName) {
        this.idUser = idUser;
        this.userName = userName;
        this.email = email;
        this.pwd = pwd;
        this.fullName = fullName;
    }
    public Users(int idUser, String userName, String email, String pwd, String fullName, String gender, String avatar) {
       this.idUser = idUser;
       this.userName = userName;
       this.email = email;
       this.pwd = pwd;
       this.fullName = fullName;
       this.gender = gender;
       this.avatar = avatar;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }




}


